# Generated by Django 5.2 on 2025-04-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
