# Generated by Django 5.2 on 2025-04-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('journal', 'Journal'), ('image', 'Image')], default='journal', max_length=10),
        ),
    ]
