# Generated by Django 5.2 on 2025-05-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='author',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='images',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='images',
            name='file_size',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='images',
            name='file_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='images',
            name='file_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='images',
            name='submitted_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
