# Generated by Django 5.2 on 2025-05-08 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_images_author_images_created_at_images_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='images',
            table='images',
        ),
    ]
