# Generated by Django 5.2 on 2025-05-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_images_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_journals',
            field=models.ManyToManyField(blank=True, related_name='assigned', to='main.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='assigned_reviewer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewer_comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='journal',
            name='assigned_reviewer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='journal',
            name='reviewer_comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='file_url',
            field=models.URLField(default='', max_length=255),
        ),
    ]
