# Generated by Django 5.2 on 2025-05-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customuser_assigned_journals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reviewed_journals',
            field=models.ManyToManyField(blank=True, related_name='reviewed', to='main.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('reviewing', 'Reviewing')], default='pending', max_length=10),
        ),
    ]
