services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_DATABASE: criminology_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
#      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the initialization scr
#      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Mount the schema script
#      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql  # Mount the seed script
    env_file:
      - .env
    networks:
      -  app-network

  #  Graphical interface for database
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network


  django:
    entrypoint: ["bash", "-e", "/app/entrypoint.sh"]
    build: .
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    env_file:
      - .env
    command: ["gunicorn", "--bind", "0.0.0.0:8000","runserver", "--workers", "3", "cirtwebsite.wsgi:application"]
    volumes:
      - .:/app  #  Mount for live updates
      - ./main/static:/app/static  # Mount static files to be accessible
    networks:
      - app-network

volumes:
  mysql_data:
  static_volume:

networks:
  app-network:
    driver: bridge
